- name: Generate XML SBOM
  uses: CycloneDX/gh-dotnet-generate-sbom@v1
  with:
    path: ./sbomgenerate/CycloneDX.sln
    github-bearer-token: ${{ secrets.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 }}

- name: Generate JSON SBOM
  uses: CycloneDX/gh-dotnet-generate-sbom@master
  with:
    path: ./sbomgenerate/CycloneDX.sln
    json: true
    github-bearer-token: ${{ secrets.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 }}
